# Generated by Django 2.1.7 on 2019-03-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=600)),
                ('email', models.CharField(max_length=300)),
            ],
        ),
    ]
