# Generated by Django 2.1.7 on 2019-03-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphapi', '0003_color_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='font',
            name='fontName',
            field=models.CharField(default='Arial', max_length=100),
            preserve_default=False,
        ),
    ]
