# Generated by Django 2.1.7 on 2019-03-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphapi', '0005_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='/media/avatars/default.svg', max_length=200),
            preserve_default=False,
        ),
    ]
