# Generated by Django 2.1.7 on 2019-03-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphapi', '0006_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='placeStatus',
            field=models.CharField(default='WAITING', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='font',
            name='placeStatus',
            field=models.CharField(default='WAITING', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.CharField(default='user', max_length=100),
            preserve_default=False,
        ),
    ]
