# Generated by Django 2.1.7 on 2019-03-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatorID', models.CharField(max_length=20)),
                ('colors', models.CharField(max_length=2000)),
            ],
        ),
    ]
