# Generated by Django 2.1.7 on 2019-03-28 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graphapi', '0008_auto_20190328_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='font',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
